import type { Discussion } from "@/types/ngn";

/**
 * Student discussion prompts. Demo responses are written to model the kind of
 * conversation NGN is trying to host: specific, reasoned, and willing to
 * concede a point. No follower counts, no rankings, no popularity metrics.
 */
export const DISCUSSIONS: Discussion[] = [
  {
    id: "disc-voting-16",
    slug: "should-voting-begin-at-16",
    question: "Should voting begin at age 16?",
    context:
      "The voting age was set at 18 nationally by the 26th Amendment in 1971. A few cities allow 16-year-olds to vote in local elections, and several countries permit it nationally. Supporters point to civic education while students are still in school; opponents question readiness and turnout.",
    relatedArticleSlugs: ["redistricting-explained"],
    relatedIssueSlugs: ["voting-elections", "education"],
    responseCount: 4,
    openedAt: "2026-08-22T15:00:00.000Z",
    cover: { pattern: "grid", hue: 210 },
    responses: [
      {
        id: "resp-1",
        author: { username: "quietcivics", displayName: "Priya R.", gradeLabel: "12th grade", hue: 280 },
        body: "The argument that convinced me isn't about maturity, it's about habit formation. Voting is habit-forming, and 16-year-olds are in a stable place — school, same address, civics class available. An 18-year-old is often moving, starting a job, or figuring out registration alone for the first time. That's the worst possible moment to ask someone to start a lifelong habit.",
        createdAt: "2026-08-22T18:12:00.000Z",
        madeMeThink: 24,
        status: "approved",
        replies: [
          {
            id: "resp-1-1",
            author: { username: "m_torres", displayName: "Marcus T.", gradeLabel: "11th grade", hue: 130 },
            body: "This is the strongest version of the case and I still land on no, but for a narrower reason than most people give. If we lower it to 16 we should also talk about what else changes at 16 — contracts, criminal responsibility, jury service. I'd want consistency rather than one-off changes.",
            createdAt: "2026-08-22T19:40:00.000Z",
            madeMeThink: 11,
            status: "approved",
            replies: [],
          },
        ],
      },
      {
        id: "resp-2",
        author: { username: "deladams", displayName: "Del A.", gradeLabel: "College first year", hue: 40 },
        body: "Something I'd want to know before deciding: in the places that already do this for local elections, what actually happened to turnout in later years? That's a testable question and I'd rather argue about the data than about whether teenagers are 'ready,' which is unfalsifiable and mildly insulting to everyone involved.",
        createdAt: "2026-08-23T09:05:00.000Z",
        madeMeThink: 31,
        status: "approved",
        replies: [],
      },
      {
        id: "resp-3",
        author: { username: "n_okafor", displayName: "Nia O.", gradeLabel: "12th grade", hue: 320 },
        body: "Counterpoint to my own side: I support this, but I don't love the argument that 16-year-olds should vote because policies affect us. Policies affect 12-year-olds too, and nobody is proposing that. The affected-by-it standard proves too much. The habit argument above is better.",
        createdAt: "2026-08-23T14:22:00.000Z",
        madeMeThink: 27,
        status: "approved",
        replies: [],
      },
      {
        id: "resp-4",
        author: { username: "jbrant", displayName: "Jonah B.", gradeLabel: "10th grade", hue: 190 },
        body: "My honest position is that I don't know yet. What I'd want is to see how a school-based registration program works first — that's a smaller change that tests part of the same idea without amending anything.",
        createdAt: "2026-08-24T11:15:00.000Z",
        madeMeThink: 9,
        status: "approved",
        replies: [],
      },
    ],
  },
  {
    id: "disc-phones",
    slug: "should-phones-be-banned-during-school",
    question: "Should phones be banned during the school day?",
    context:
      "States and districts have adopted policies ranging from full-day restrictions to class-time-only rules. Almost all include exceptions for medical needs and disability accommodations. Students are rarely consulted before adoption.",
    relatedArticleSlugs: ["phones-in-schools-policy-explained"],
    relatedIssueSlugs: ["education", "technology"],
    responseCount: 3,
    openedAt: "2026-08-20T13:00:00.000Z",
    cover: { pattern: "grid", hue: 240 },
    responses: [
      {
        id: "resp-p1",
        author: { username: "sara_l", displayName: "Sara L.", gradeLabel: "11th grade", hue: 260 },
        body: "My school went bell-to-bell this year and I expected to hate it. The classroom part is genuinely better — I notice it. Lunch is the part I'd push back on, because that's when people actually coordinate rides and shifts. The distinction between class time and the whole day matters way more than the ban-versus-no-ban framing.",
        createdAt: "2026-08-20T17:30:00.000Z",
        madeMeThink: 42,
        status: "approved",
        replies: [
          {
            id: "resp-p1-1",
            author: { username: "teacher_kim", displayName: "Ms. Kim", gradeLabel: "Educator", hue: 150 },
            body: "From the other side of the desk: the reason full-day policies exist is that partial policies push enforcement onto individual teachers, and then it gets applied inconsistently, which students correctly perceive as unfair. Not saying that settles it — just that the enforcement problem is real and under-discussed.",
            createdAt: "2026-08-20T20:05:00.000Z",
            madeMeThink: 38,
            status: "approved",
            replies: [],
          },
        ],
      },
      {
        id: "resp-p2",
        author: { username: "andre_v", displayName: "Andre V.", gradeLabel: "12th grade", hue: 90 },
        body: "The emergency argument gets used a lot and I think it's the weakest one on my side. School safety guidance generally says to contact the office rather than individual students. I still oppose full-day bans, but I want to argue for that honestly rather than with a reason that doesn't hold up.",
        createdAt: "2026-08-21T08:44:00.000Z",
        madeMeThink: 35,
        status: "approved",
        replies: [],
      },
      {
        id: "resp-p3",
        author: { username: "hana_w", displayName: "Hana W.", gradeLabel: "10th grade", hue: 20 },
        body: "Whatever the policy is, the exception process needs to be written down and automatic for people with medical devices. At my school it's technically allowed but you have to ask an administrator every time, which means in practice people just break the rule instead.",
        createdAt: "2026-08-21T15:52:00.000Z",
        madeMeThink: 29,
        status: "approved",
        replies: [],
      },
    ],
  },
  {
    id: "disc-generation-issue",
    slug: "what-issue-matters-most-to-your-generation",
    question: "What political issue matters most to your generation — and what do adults get wrong about it?",
    context:
      "Polling on youth political priorities varies substantially by how the question is asked. This thread is about your own reasoning, not about what surveys say.",
    relatedArticleSlugs: ["why-prices-still-feel-high", "why-car-rules-became-a-climate-fight"],
    relatedIssueSlugs: ["economy", "climate-change"],
    responseCount: 3,
    openedAt: "2026-08-19T12:00:00.000Z",
    cover: { pattern: "arc", hue: 160 },
    responses: [
      {
        id: "resp-g1",
        author: { username: "ellis_j", displayName: "Ellis J.", gradeLabel: "College first year", hue: 200 },
        body: "Housing. And the thing adults get wrong is treating it as a young-person complaint about wanting things. It's a supply question with actual policy answers — zoning, permitting, construction financing. When it gets framed as generational grievance instead of as land use policy, nothing gets built.",
        createdAt: "2026-08-19T16:20:00.000Z",
        madeMeThink: 46,
        status: "approved",
        replies: [],
      },
      {
        id: "resp-g2",
        author: { username: "tomas_r", displayName: "Tomas R.", gradeLabel: "12th grade", hue: 70 },
        body: "Climate, but not in the way it usually gets covered. The debate I actually care about is permitting and transmission lines, which is boring and technical and decides more than any pledge. I'd trade ten speeches for one grid interconnection reform.",
        createdAt: "2026-08-20T10:11:00.000Z",
        madeMeThink: 33,
        status: "approved",
        replies: [],
      },
      {
        id: "resp-g3",
        author: { username: "amara_b", displayName: "Amara B.", gradeLabel: "11th grade", hue: 300 },
        body: "Mental health services in schools. What adults get wrong: they think the ask is more awareness campaigns. The ask is a counselor you can actually get an appointment with in under three weeks.",
        createdAt: "2026-08-20T19:03:00.000Z",
        madeMeThink: 51,
        status: "approved",
        replies: [],
      },
    ],
  },
  {
    id: "disc-social-media",
    slug: "should-social-media-face-stricter-regulation",
    question: "Should social media companies face stricter regulation?",
    context:
      "Proposals range from privacy defaults for minors to design requirements to changes in Section 230. Courts have limited some state laws on First Amendment grounds. Research on adolescent effects is actively contested.",
    relatedArticleSlugs: ["supreme-court-online-speech-explained", "who-gets-to-regulate-ai"],
    relatedIssueSlugs: ["technology"],
    responseCount: 3,
    openedAt: "2026-08-17T14:00:00.000Z",
    cover: { pattern: "orbit", hue: 250 },
    responses: [
      {
        id: "resp-s1",
        author: { username: "kai_m", displayName: "Kai M.", gradeLabel: "12th grade", hue: 230 },
        body: "I want to separate two things people mash together: rules about what companies can collect about minors, and rules about what content can be shown. The first seems much easier to justify and much harder to abuse. The second gives whoever is in power a lever over speech, and that should worry you regardless of who is in power right now.",
        createdAt: "2026-08-17T18:41:00.000Z",
        madeMeThink: 44,
        status: "approved",
        replies: [
          {
            id: "resp-s1-1",
            author: { username: "lena_p", displayName: "Lena P.", gradeLabel: "College second year", hue: 340 },
            body: "Agreed on the distinction. I'd add a third category: design requirements like default settings and time-of-day limits, which are neither data rules nor content rules. That's where most of the workable proposals actually sit.",
            createdAt: "2026-08-17T21:15:00.000Z",
            madeMeThink: 22,
            status: "approved",
            replies: [],
          },
        ],
      },
      {
        id: "resp-s2",
        author: { username: "owen_f", displayName: "Owen F.", gradeLabel: "11th grade", hue: 110 },
        body: "The research point in the article is the one I keep coming back to. If credible studies genuinely disagree about the size of the effect, then confident regulation based on 'we all know it's harmful' is building on something unstable. I'd rather have transparency requirements that let researchers settle it first.",
        createdAt: "2026-08-18T09:27:00.000Z",
        madeMeThink: 30,
        status: "approved",
        replies: [],
      },
      {
        id: "resp-s3",
        author: { username: "j_delacruz", displayName: "Josie D.", gradeLabel: "10th grade", hue: 10 },
        body: "Whatever gets passed should apply to the small platforms too. Every version I've read has a user-count threshold, which means the rules stop applying exactly where moderation is worst.",
        createdAt: "2026-08-18T16:50:00.000Z",
        madeMeThink: 26,
        status: "approved",
        replies: [],
      },
    ],
  },
  {
    id: "disc-compromise",
    slug: "is-compromise-underrated-or-overrated",
    question: "Is political compromise underrated, or is it sometimes just losing slowly?",
    context:
      "Bipartisanship is often treated as automatically good. Critics on both sides argue that compromise can entrench a bad status quo or trade away something that should not be traded.",
    relatedArticleSlugs: ["government-funding-deadline-explained"],
    relatedIssueSlugs: ["voting-elections"],
    responseCount: 2,
    openedAt: "2026-08-15T10:00:00.000Z",
    cover: { pattern: "column", hue: 45 },
    responses: [
      {
        id: "resp-c1",
        author: { username: "rhea_s", displayName: "Rhea S.", gradeLabel: "College first year", hue: 180 },
        body: "Compromise is a method, not a value. Whether it's good depends entirely on what's being traded. The useful question isn't 'did both sides give something up' — it's 'is the resulting policy better than the alternative that was actually available,' which is different from the alternative you wish had been available.",
        createdAt: "2026-08-15T13:30:00.000Z",
        madeMeThink: 39,
        status: "approved",
        replies: [],
      },
      {
        id: "resp-c2",
        author: { username: "beckett_n", displayName: "Beckett N.", gradeLabel: "12th grade", hue: 60 },
        body: "The thing that changed my mind: most bills that pass are boring and bipartisan, and nobody covers them. The dramatic fights are a small and unrepresentative sample of what Congress actually does. That reframed compromise for me from 'weak' to 'normal.'",
        createdAt: "2026-08-16T11:08:00.000Z",
        madeMeThink: 34,
        status: "approved",
        replies: [],
      },
    ],
  },
  {
    id: "disc-civics",
    slug: "should-civics-be-required-every-year",
    question: "Should civics be a required class every year of high school?",
    context:
      "Most states require a single semester or year of civics or government. Curriculum requirements are set at the state level, and adding a requirement usually means removing something else.",
    relatedArticleSlugs: ["phones-in-schools-policy-explained"],
    relatedIssueSlugs: ["education"],
    responseCount: 2,
    openedAt: "2026-08-14T09:00:00.000Z",
    cover: { pattern: "ridge", hue: 200 },
    responses: [
      {
        id: "resp-cv1",
        author: { username: "imani_k", displayName: "Imani K.", gradeLabel: "11th grade", hue: 290 },
        body: "Yes, but only if it's current-events based rather than another pass through the three branches. I could recite the branches in seventh grade and still had no idea what a continuing resolution was until last month.",
        createdAt: "2026-08-14T12:45:00.000Z",
        madeMeThink: 28,
        status: "approved",
        replies: [],
      },
      {
        id: "resp-cv2",
        author: { username: "gabe_ortiz", displayName: "Gabe O.", gradeLabel: "12th grade", hue: 100 },
        body: "The hard part is what you cut to make room. Every subject thinks it deserves more time. I'd rather see civics built into English and history requirements than added as a separate class that competes with electives people actually need.",
        createdAt: "2026-08-14T18:20:00.000Z",
        madeMeThink: 21,
        status: "approved",
        replies: [],
      },
    ],
  },
];
