import Anthropic from "@anthropic-ai/sdk";
import { getArticleBySlug } from "@/lib/content/repository";
import {
  ASK_SYSTEM_PROMPT,
  DRAFT_SYSTEM_PROMPT,
  EXPLAIN_SYSTEM_PROMPT,
  buildDraftUserMessage,
} from "./prompts";
import type {
  AiProvider,
  AskResponse,
  DraftRequest,
  ExplainMode,
  ExplainResponse,
  GeneratedDraft,
} from "./types";

/**
 * Live Claude provider.
 *
 * Only constructed when ANTHROPIC_API_KEY is present — see `lib/ai/index.ts`.
 * Nothing in the UI depends on this file existing at runtime, so the product
 * works fully without credentials.
 */

export const NGN_MODEL = "claude-opus-5";

function client() {
  return new Anthropic();
}

function textOf(message: Anthropic.Message) {
  return message.content
    .filter((block): block is Anthropic.TextBlock => block.type === "text")
    .map((block) => block.text)
    .join("\n")
    .trim();
}

/** Model output is JSON by instruction; tolerate a stray code fence. */
function parseJson<T>(raw: string): T {
  const fenced = raw.match(/```(?:json)?\s*([\s\S]*?)```/);
  return JSON.parse(fenced ? fenced[1] : raw) as T;
}

/** The only material a reader-facing answer may be grounded in. */
async function approvedMaterial(slug: string) {
  const article = await getArticleBySlug(slug);
  if (!article) return null;
  return [
    `HEADLINE: ${article.headline}`,
    `SUMMARY: ${article.summary}`,
    `IN 20 SECONDS: ${article.inTwentySeconds}`,
    `WHAT HAPPENED: ${article.quickWhatHappened}`,
    `WHY IT MATTERS: ${article.quickWhyItMatters}`,
    `WHAT HAPPENS NEXT: ${article.quickWhatNext}`,
    `BODY:\n${article.body.map((s) => `${s.heading}\n${s.paragraphs.join("\n")}`).join("\n\n")}`,
    `DEMOCRATIC PERSPECTIVE: ${article.democraticView.summary} ${article.democraticView.points.join(" ")}`,
    `REPUBLICAN PERSPECTIVE: ${article.republicanView.summary} ${article.republicanView.points.join(" ")}`,
    `OTHER PERSPECTIVES: ${article.otherViews.map((v) => `${v.label}: ${v.summary}`).join(" ")}`,
    `WHAT WE KNOW: ${article.knownFacts.join(" ")}`,
    `WHAT IS UNCLEAR: ${article.uncertainties.join(" ")}`,
    `KEY TERMS: ${article.keyTerms.map((t) => `${t.term} — ${t.definition}`).join("; ")}`,
    `SOURCES: ${article.sources.map((s) => `${s.publisher}: ${s.title}`).join("; ")}`,
  ].join("\n\n");
}

async function generateDraft(request: DraftRequest): Promise<GeneratedDraft> {
  // Drafts are long, so stream to stay clear of request timeouts.
  const stream = client().messages.stream({
    model: NGN_MODEL,
    max_tokens: 32000,
    thinking: { type: "adaptive" },
    output_config: { effort: "high" },
    system: DRAFT_SYSTEM_PROMPT,
    messages: [{ role: "user", content: buildDraftUserMessage(request) }],
  });

  const message = await stream.finalMessage();
  const draft = parseJson<GeneratedDraft>(textOf(message));

  return {
    ...draft,
    sources: (draft.sources ?? []).map((source, index) => ({
      ...source,
      id: source.id ?? `generated-source-${index + 1}`,
      // Nothing generated is treated as a verified citation until an editor says so.
      isPlaceholder: true,
    })),
    editorNotes: [
      ...(draft.editorNotes ?? []),
      "Generated by Claude. Requires human review of every field before publication.",
    ],
  };
}

async function explain(
  slug: string,
  mode: ExplainMode,
): Promise<ExplainResponse> {
  const material = await approvedMaterial(slug);
  if (!material) {
    return {
      mode,
      title: "Nothing to explain yet",
      paragraphs: ["This story has no approved material to explain from."],
    };
  }

  const message = await client().messages.create({
    model: NGN_MODEL,
    max_tokens: 4000,
    thinking: { type: "adaptive" },
    output_config: { effort: "medium" },
    system: EXPLAIN_SYSTEM_PROMPT,
    messages: [
      {
        role: "user",
        content: `Mode: ${mode}\n\nApproved material:\n${material}\n\nRespond as JSON: { "title": string, "paragraphs": string[], "terms": [{ "term": string, "definition": string }] }`,
      },
    ],
  });

  const parsed = parseJson<Omit<ExplainResponse, "mode">>(textOf(message));
  return { mode, ...parsed };
}

async function ask(slug: string, question: string): Promise<AskResponse> {
  const material = await approvedMaterial(slug);
  if (!material) {
    return {
      answer: "That story is not available, so there is nothing to answer from.",
      citations: [],
      outOfScope: true,
    };
  }

  const message = await client().messages.create({
    model: NGN_MODEL,
    max_tokens: 2000,
    thinking: { type: "adaptive" },
    output_config: { effort: "medium" },
    system: ASK_SYSTEM_PROMPT,
    messages: [
      {
        role: "user",
        content: `Reader question: ${question}\n\nApproved material:\n${material}\n\nRespond as JSON: { "answer": string, "citations": string[], "outOfScope": boolean }`,
      },
    ],
  });

  return parseJson<AskResponse>(textOf(message));
}

export const claudeProvider: AiProvider = {
  name: "claude",
  generateDraft,
  explain,
  ask,
};
